### ISSUE TITLE
AUTHORS

### ISSUE THREAD

**Issue by varlesh** [jcmljunior/Adapta-OSX#1]
You use my sources:
https://raw.githubusercontent.com/PapirusDevelopmentTeam/adapta-kde/master/aurorae/themes/Adapta/decoration.svg
https://raw.githubusercontent.com/jcmljunior/Adapta-OSX/master/Adapta-OSX/decoration.svg
Where AUTHORS?
https://github.com/PapirusDevelopmentTeam/adapta-kde/blob/master/aurorae/themes/Adapta/AUTHORS

**Comment by jcmljunior** [comment]
Hi @varlesh
Could you check if everything is all right now?
Thanks

**Comment by varlesh** [comment]
No. I mean file AUTHORS on theme. 
For example:

> Based on Adapta KDE Aurorae Theme by Alexey Varfolomeev:
> https://github.com/PapirusDevelopmentTeam/adapta-kde

and etc...

**Comment by jcmljunior** [comment]
You talk about it, do not you?
https://github.com/jcmljunior/Adapta-OSX/blob/master/AUTHORS

**Comment by jcmljunior** [comment]
if you can edit the file, I would appreciate it.
I use the translator, I do not understand English very well.
Sorry for the problem.
Thanks!

**Comment by jcmljunior** [comment]
I made modifications to the file "readme.md".
Confirm me if this is all right now, okay?
Thanks

**Comment by varlesh** [comment]
Ok, thx!
